addition of SGE support for moedivconmpi. the addition has been tested on current versions of SGE and it works. the user MUST ask for the SGE PE (parallel environment) in order for it to work.
git-svn-id: https://svn.quantumbioinc.com/MOEDivcon/trunk@7167 0241862a-156b-41b8-859c-7af79c85dedb

diff --git a/bin/moedivconmpi b/bin/moedivconmpi
--- a/bin/moedivconmpi
+++ b/bin/moedivconmpi
@@ -23,11 +23,29 @@ fi
 if [ -e "qbmachinefile.txt" ] ; then
     QBMACHINEFILE="-machinefile qbmachinefile.txt"
 elif [ ! -z "${PBS_NODEFILE}" ]; then
-# NOTE!! We should use mpirun technologies as per ticket #553 instead of doing it this way.
+# Using PBS to machinefile
     QBMACHINEFILE="-machinefile ${PBS_NODEFILE}"
+elif [ ! -z "${PE_HOSTFILE}" ]; then
+# Using SGE for machinefile
+    cat ${PE_HOSTFILE}
+    rm -f sge_machinefile.txt
+    QBMACHINEFILE="-machinefile sge_machinefile.txt"
+    cat ${PE_HOSTFILE} | while read line; do
+        host=`echo $line|cut -f1 -d" "|cut -f1 -d"."`
+        nslots=`echo $line|cut -f2 -d" "`
+        i=1
+        while [ $i -le $nslots ]; do
+            echo $host >> sge_machinefile.txt
+            i=`expr $i + 1`
+        done
+    done
 else
 # We need an empty QBMACHINEFILE variable for the mpirun below so we don't need to maintain two calls.
     QBMACHINEFILE=""
+#    echo "ERROR: machinefile must be provided (e.g. qbmachinefile.txt) or PBS or PE SGE must be used."
+#    exit 1
 fi
 
 ${QBHOME}/bin/mpirun -x OPAL_PREFIX -x QBHOME -x PATH -x LD_LIBRARY_PATH -x MKL_NUM_THREADS -x MKL_DYNAMIC ${QBMACHINEFILE} ${QBHOME}/bin/moedivconmpi.bin $@ - 
+
+
