Added support for proper DivCon app version searching on GridMarkets. This allows the script to automatically update and report the correct DivCon app version when invoked.

diff --git a/bin/qmechanic b/bin/qmechanic
--- a/bin/qmechanic
+++ b/bin/qmechanic
@@ -37,11 +37,11 @@ fi
 
 if [[ $EXEC_LOCATION == *"gridmarkets"* ]]; then
     if ! [ -x "$(command -v jq)" ]; then
-      echo 'Error: jq is not installed. jq is required in order to execute cloud-based tools.' >&2
+      echo 'Error: jq is not installed. jq is required in order to execute cloud-based DivCon tools.' >&2
       exit 1
     fi
     if ! [ -x "$(command -v curl)" ]; then
-      echo 'Error: curl is not installed. curl is required in order to execute cloud-based tools.' >&2
+      echo 'Error: curl is not installed. curl is required in order to execute cloud-based DivCon tools.' >&2
       exit 1
     fi
 
@@ -57,11 +57,30 @@ if [[ $EXEC_LOCATION == *"gridmarkets"* ]]; then
              COMM_LIST[${#COMM_LIST[@]}]="$i"
          fi
     done
+    TESTDATA=$( curl -isS ${ENVOY_URL} 2>&1 >/dev/null )
+    echo $TESTDATA
+    if [[ $TESTDATA == *"Connection refused"* ]]; then
+        echo "ERROR: Envoy is not running at $ENVOY_URL. Please start Envoy and try again.\m    Visit https://www.pharma.gridmarkets.com/ for more information or to download Envoy."
+    else
 
-    FILELIST=`echo ${COMM_LIST[@]} | sed 's/ /\n/g' | jq --slurp --raw-input 'split("\n")[:-1]'`
+        AUTHDATA=$( curl -s  ${ENVOY_URL}/auth )
+        username=`echo ${AUTHDATA} | jq '.Username'`
+        AUTHDATA=$( curl -s  ${ENVOY_URL}/user-info )
+        credits_available=`echo ${AUTHDATA} | jq '.data.credits_available'`
+        AUTHDATA=$( curl -s  ${ENVOY_URL}/info )
+        envoy_version=`echo ${AUTHDATA} | jq '.version'`
+        AUTHDATA=$( curl -s  ${ENVOY_URL}/products )
+        export divcon_version=`echo ${AUTHDATA} | jq '[.[] | select(.app_type=="divcon")] | .[-1] | .version'`
 
-    #read -r -d '' SUBTEMP << EOM
-    SUBTEMP=$(cat <<-EOM
+        echo "Envoy Version:     ${envoy_version}"
+        echo "DivCon Version:    ${divcon_version}"
+        echo "Username:          ${username}"
+        echo "Credits Available: ${credits_available}"
+
+        FILELIST=`echo ${COMM_LIST[@]} | sed 's/ /\n/g' | jq --slurp --raw-input 'split("\n")[:-1]'`
+
+        #read -r -d '' SUBTEMP << EOM
+        SUBTEMP=$(cat <<-EOM
 {
   "project_files": {
     "localRoot": "${PWD}",
@@ -77,7 +96,7 @@ if [[ $EXEC_LOCATION == *"gridmarkets"* ]]; then
         "id": "job-DC",
         "name": "DivCon-${SUBNAME}",
         "app": "divcon",
-        "app_version": "2022-b4909",
+        "app_version": ${divcon_version},
         "operation": "simulation",
         "machine_type": "gm3200",
         "path": "/${SUBNAME}",
@@ -95,31 +114,12 @@ if [[ $EXEC_LOCATION == *"gridmarkets"* ]]; then
 EOM
     )
 
-    echo ${SUBTEMP} | envsubst | jq . >& DEBUG.json
-
-    divcon_version=`echo ${SUBTEMP} | jq '.project_request.jobs[0].app_version'`
-
-    TESTDATA=$( curl -isS ${ENVOY_URL} 2>&1 >/dev/null )
-    echo $TESTDATA
-    if [[ $TESTDATA == *"Connection refused"* ]]; then
-        echo "ERROR: Envoy is not running at $ENVOY_URL. Please start Envoy and try again.\m    Visit https://www.pharma.gridmarkets.com/ for more information or to download Envoy."
-    else
-        AUTHDATA=$( curl -s  ${ENVOY_URL}/auth )
-        username=`echo ${AUTHDATA} | jq '.Username'`
-        AUTHDATA=$( curl -s  ${ENVOY_URL}/user-info )
-        credits_available=`echo ${AUTHDATA} | jq '.data.credits_available'`
-        AUTHDATA=$( curl -s  ${ENVOY_URL}/info )
-        envoy_version=`echo ${AUTHDATA} | jq '.version'`
-
-        echo "Envoy Version:     ${envoy_version}"
-        echo "DivCon Version:    ${divcon_version}"
-        echo "Username:          ${username}"
-        echo "Credits Available: ${credits_available}"
-        echo "  Visit ${ENVOY_UI_URL} to manage GridMarkets job ${SUBNAME}"
+        echo ${SUBTEMP} | envsubst | jq . >& DEBUG.json
         
         SUBMITDATA=$( curl -s -X POST  ${ENVOY_URL}/project-submit -H "${DATA_HEADER}" -d "${SUBTEMP}" )
 
         echo ${SUBMITDATA}
+        echo "  Visit ${ENVOY_UI_URL} to manage GridMarkets job ${SUBNAME}"
     fi
 
 elif [[ $EXEC_LOCATION == *"local"* ]]; then
